### DISCUSSION TITLE
Custom:html-card - html issue of filling the card without margins

### DISCUSSION THREAD

**Discussion by MD0005** [PiotrMachowski/Home-Assistant-Lovelace-HTML-Jinja2-Template-card#29] [Q&A] [answered]
Hello. I have encountered an issue that might be very basic for some, but for me its imposible, even with html tutorials.
Im trying to fill up the custom:htm-card completely, but keep having the top/bottom and left/right margins. I would appreciate hints regarding the below code. What im trying to ahieve is to fill up the card without margins and if possible, keep its relativity to the card size (to layout options).

This is the closest I could get:

```
type: custom:html-card
content: >
  <span style="position:relative; left:-16px; top:-16px"><video width="107%"
  autoplay loop muted playsinline> <source
  src="https://imageserver.webcamera.pl/rec/krakow2/latest.mp4"
  type="video/mp4"> </video></span>
layout_options:
  grid_columns: 4
  grid_rows: 4
```

**Comment by PiotrMachowski** [comment, marked as answer]
Use [this card](https://github.com/PiotrMachowski/Home-Assistant-Lovelace-HTML-Jinja2-Template-card) with the following config:
```yaml
type: custom:html-template-card
content: >
  <video width="100%" autoplay loop muted playsinline>
  <source src="https://imageserver.webcamera.pl/rec/wroclaw/latest.mp4" type="video/mp4">
  </video>
do_not_parse: true
picture_elements_mode: true

```
