### ISSUE TITLE
Icon size

### ISSUE THREAD

**Issue by topcat36** [PiotrMachowski/Home-Assistant-Lovelace-HTML-Jinja2-Template-card#20]
Hello,

Is there a way to increase the icon size ? Some extra parameters like:

`<ha-icon icon="mdi:car-battery" {size=150%}></ha-icon>`

Thanks.

**Comment by PiotrMachowski** [comment]
```yaml
type: custom:html-template-card
content: |
  <ha-icon icon="mdi:car-battery" style="--mdc-icon-size: 40px;"></ha-icon>
  <ha-icon icon="mdi:car-battery" style="--mdc-icon-size: 90px;"></ha-icon>
```

Default size is 24px
