### ISSUE TITLE
Styles in <body> tag or internal CSS are not applied

### ISSUE THREAD

**Issue by pfh-47** [PiotrMachowski/Home-Assistant-Lovelace-HTML-Jinja2-Template-card#30]
I am using the (brilliant!) Jinja and HTML features of this component to create the content for a card but cannot set the background colour for the whole card. Here is some code to illustrate the problem.

`type: custom:html-template-card
ignore_line_breaks: true
content: |
  <!DOCTYPE html>
    <html>
      <head>
      </head>
        <body style="background-color:blue;">       
          <p>Hello world</p>
        </body>
    </html>`
This W3 Schools tutorial shows how it could work: [https://www.w3schools.com/cssref/pr_background-color.php](url)

I can set the background colour within a `<div>` element but this is not the effect I am looking for

`type: custom:html-template-card
ignore_line_breaks: true
content: |
  <!DOCTYPE html>
    <html>
      <head>
      </head>
        <body>       
          <div style="background-color:blue;">
            <p>Hello world</p>
          </div>
        </body>
    </html>`

**Comment by PiotrMachowski** [comment]
You can't use <body> inside the card - it is not a separate page.

If you want to take control of the whole content of the card you can use the following configs:

```yaml
type: custom:html-template-card
ignore_line_breaks: true
picture_elements_mode: true
content: |
  <div style="background: red"> 
  <p>Hello world</p>
  </div>
```

or

```yaml
type: custom:html-template-card
ignore_line_breaks: true
picture_elements_mode: true
content: |
  <ha-card style="background: red">
  <p>Hello world</p>
  </ha-card>
```
